### ISSUE TITLE
I am being charged a commission for unlocking and withdrawal that I consider absurd

### ISSUE THREAD

**Issue by piero6758** [Steemhunt/neverlose.money-contract#17] opened 2020-12-27 15:31 UTC
**Describe the bug**

I wanted to retire, I know that they would charge me 10% for breaking the withdrawal contract before completing the lockdown period, in addition they would also charge me 3% for the treasury fund.

Is that after proceeding to unblock and withdraw they send me to my Metamask wallet where they are charging me an unknown commission of $ 39.28.

This commission is really unfair, since I did not know about it.

**To Reproduce**

**Expected behavior**

I expected to withdraw and only that they would charge me 10% and 3% commission. I didn't expect that they would also charge me another commission.

**Screenshots**

https://prntscr.com/wavq3s

**Additional context**

**Bounty information**
1. Reporter's email address: geanpieroechenique@gmail.com
2. What crypto currency do you want to receive the bounty?: BTC 
2. Wallet address to receive the bounty: 38oQPChubpMuWJpuWw6HRRZXDLiA5Qa8Bm

**Comment by sydneyitguy** [comment] 2020-12-29 02:30
That's not the commission we take.
That is a gas fee you need to pay for "any transaction" you broadcast on Ethereum network.

Gas fee has increased a lot recently due to heavy usage on Ethereum network. It's has become more than 50 times expensive than about 3-4 months ago, but it can decrease or even increase more depending on the scalability of Ethereum and network usage.
You can track the gas price here: https://etherscan.io/gastracker

Anyway, it's not a bug, and not a commission we take.
I will close this issue.

**Closed by sydneyitguy** 2020-12-29 02:30 UTC
Labels: bug
